package com.ledgerlens.entity.enums;

public enum ExceptionType {
    AMOUNT_MISMATCH,
    MISSING_PAYMENT,
    MISSING_SETTLEMENT,
    UNEXPECTED_FEE,
    DUPLICATE_TRANSACTION,
    DELAYED_SETTLEMENT,
    DISCREPANT_REFUND,
    UNKNOWN_TRANSACTION,
    UNMATCHED_ADJUSTMENT,
    CURRENCY_MISMATCH,
    DATA_INCOMPLETE
}
