package com.ledgerlens.dto;

import java.math.BigDecimal;
import java.util.List;

/**
 * Phase 3.5: Evidence Sufficiency Assessment
 * 
 * Deterministic backend assessment of whether sufficient evidence exists
 * for the AI to perform forensic reasoning on this exception.
 * 
 * THIS IS A BACKEND SCORE - NOT GENERATED BY GEMINI.
 */
public class EvidenceSufficiencyDto {

    private BigDecimal sufficiencyScore;  // 0-100, deterministically calculated
    private String assessment;  // SUFFICIENT, PARTIAL, INSUFFICIENT
    private List<String> foundEvidence;
    private List<String> missingEvidence;
    private String reasoning;  // Why this score was assigned

    public EvidenceSufficiencyDto() {}

    public EvidenceSufficiencyDto(BigDecimal sufficiencyScore, String assessment,
                                 List<String> foundEvidence, List<String> missingEvidence,
                                 String reasoning) {
        this.sufficiencyScore = sufficiencyScore;
        this.assessment = assessment;
        this.foundEvidence = foundEvidence;
        this.missingEvidence = missingEvidence;
        this.reasoning = reasoning;
    }

    public static EvidenceSufficiencyDtoBuilder builder() { return new EvidenceSufficiencyDtoBuilder(); }

    public BigDecimal getSufficiencyScore() { return sufficiencyScore; }
    public void setSufficiencyScore(BigDecimal sufficiencyScore) { this.sufficiencyScore = sufficiencyScore; }

    public String getAssessment() { return assessment; }
    public void setAssessment(String assessment) { this.assessment = assessment; }

    public List<String> getFoundEvidence() { return foundEvidence; }
    public void setFoundEvidence(List<String> foundEvidence) { this.foundEvidence = foundEvidence; }

    public List<String> getMissingEvidence() { return missingEvidence; }
    public void setMissingEvidence(List<String> missingEvidence) { this.missingEvidence = missingEvidence; }

    public String getReasoning() { return reasoning; }
    public void setReasoning(String reasoning) { this.reasoning = reasoning; }

    public static class EvidenceSufficiencyDtoBuilder {
        private BigDecimal sufficiencyScore;
        private String assessment;
        private List<String> foundEvidence;
        private List<String> missingEvidence;
        private String reasoning;

        public EvidenceSufficiencyDtoBuilder sufficiencyScore(BigDecimal sufficiencyScore) { this.sufficiencyScore = sufficiencyScore; return this; }
        public EvidenceSufficiencyDtoBuilder assessment(String assessment) { this.assessment = assessment; return this; }
        public EvidenceSufficiencyDtoBuilder foundEvidence(List<String> foundEvidence) { this.foundEvidence = foundEvidence; return this; }
        public EvidenceSufficiencyDtoBuilder missingEvidence(List<String> missingEvidence) { this.missingEvidence = missingEvidence; return this; }
        public EvidenceSufficiencyDtoBuilder reasoning(String reasoning) { this.reasoning = reasoning; return this; }

        public EvidenceSufficiencyDto build() {
            return new EvidenceSufficiencyDto(sufficiencyScore, assessment, foundEvidence, missingEvidence, reasoning);
        }
    }
}
